server:
  port: 8081

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Beaconfire-Time-Sheet-Flow/ConfigDocs.git
#          username: helloway920
#          password: Wangbinwei920*
          force-pull: true
          clone-on-start: true
          default-label: main

management:
  security:
    enabled=false: